### ISSUE TITLE
run pscout with android 6.0 or higher

### ISSUE THREAD

**Issue by DSOTM-pf** [EnSoftCorp/AnalyzableAndroid#1]
Hello, i am a student want exercise static analysis . 
 I use this [manner](https://github.com/EnSoftCorp/AnalyzableAndroid/tree/master/Android22) run with API 23 and higher .
1: when i run command ```../bin/dumpclass.ch``` ,there was many errors ,like ```can not find files...```. Than the output of mappings is inaccurate(very) . Do you have any idea? 
2:I find axplorer , it has better mappings less than API 25 , but it just has data.
3:It is five years age repository, longtime but useful for me . 
Thanks

**Comment by DSOTM-pf** [comment]
This is part log in ```err``` file in ```ANDROID_CLASS_DIR```,actual errors are more.
```
Exception in thread "main" java.lang.RuntimeException: Could not load classfile: java.lang.CharSequence
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:194)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:140)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.tryLoadClass(Scene.java:406)
	at soot.Scene.loadBasicClasses(Scene.java:971)
	at dump.DumpClass.main(DumpClass.java:16)
Exception in thread "main" java.lang.RuntimeException: Could not load classfile: java.lang.CharSequence
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:194)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:140)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.tryLoadClass(Scene.java:406)
	at soot.Scene.loadBasicClasses(Scene.java:971)
	at dump.DumpClass.main(DumpClass.java:16)
```

**Comment by benjholla** [comment]
I do not believe PScout will run on APIs 25+. The Android build system continued to evolve from each version of Android. I forked PScout (https://github.com/benjholla/pscout) and made some changes in order to get it run for versions up to maybe version 22. Each version I had to figure out what changed and then fix the build scripts in PScout to work, however I don't know if that will be enough anymore. The axplorer tool succeeded PScout and I did port its mappings over to the collection of mappings I was making for the Android Toolbox (https://github.com/EnSoftCorp/android-essentials-toolbox/tree/master/com.ensoftcorp.open.android.essentials/src/com/ensoftcorp/open/android/essentials/permissions/mappings). I don't think there has been any recent work on recovering Android permission mappings.

**Comment by DSOTM-pf** [comment]
Thanks for your reply .
It's means that if I want to run PScout on a certain version, I must adapt the new features of this version ? This sound a bit difficult ,related to AOSP . I will try it  , if that doesn't work , i  can only use old mappings.
Your [project](https://github.com/EnSoftCorp/android-essentials-toolbox)  has helpful for my learning , Thanks !
